import { Inter } from "next/font/google";

import { AccessTokenProvider } from "@/contexts/accessToken";
import "./globals.css";
import { TracksProvider } from "@/contexts/tracks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Playlist Maker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AccessTokenProvider>
      <TracksProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </TracksProvider>
    </AccessTokenProvider>
  );
}
